In [74]:
import pandas as pd

In [75]:
# Load dataset
df = pd.read_csv("C:/DSML/Jobs/2026/Internship/SkillAudit/CafeProject/data/raw/dirty_cafe_sales.csv")

In [76]:
# Display first 5 rows
df.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [62]:
# Display total rows and columns
df.shape

(10000, 8)

In [ ]:
# Display column names
df.columns

In [ ]:
# Display datatypes
df.dtypes

In [ ]:
df.info()

In [ ]:
# Check duplicate values
df.duplicated().sum()

In [ ]:
# Null / Missing values
df.isnull().sum()

In [ ]:
(df.isnull().sum() / len(df) * 100).round(2)

In [ ]:
# Checking for invalid values in categorical columns
df['Item'].value_counts(dropna=False)
df['Payment Method'].value_counts(dropna=False)
df['Location'].value_counts(dropna=False)

In [ ]:
# Checking Uniqueness in categorical columns

df['Item'].unique()
df['Item'].nunique()

In [ ]:
df['Payment Method'].unique()
df['Payment Method'].nunique()

In [ ]:
df['Location'].unique()
df['Location'].nunique()

In [ ]:
df.describe()

In [77]:
# Creating copies of dataset
df_raw = df.copy()
df_clean = df.copy()

In [78]:
# Standardize column names

df_clean.columns = (
    df_clean.columns
    .str.strip()
    .str.lower()
    .str.replace(" ", "_")
)

In [ ]:
df_clean.columns

In [79]:
df_clean.head()

,transaction_id,item,quantity,price_per_unit,total_spent,payment_method,location,transaction_date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [80]:
# Cleaning text fields
df_clean["item"] = df_clean["item"].str.strip()
df_clean["payment_method"] = df_clean["payment_method"].str.strip()
df_clean["location"] = df_clean["location"].str.strip()

In [81]:
df_clean.head()

,transaction_id,item,quantity,price_per_unit,total_spent,payment_method,location,transaction_date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [47]:
import numpy as np

In [82]:
# Converting placeholder to missing values
invalid_values = ['UNKNOWN', 'ERROR', 'Unknown', 'unknown']

df_clean = df_clean.replace(invalid_values,np.nan)

In [83]:
# Convert numeric columns
df_clean["quantity"] = pd.to_numeric(
    df_clean["quantity"],
    errors = 'coerce'
)

In [84]:
df_clean["price_per_unit"] = pd.to_numeric(
    df_clean["price_per_unit"],
    errors = 'coerce'
)

In [85]:
df_clean["total_spent"] = pd.to_numeric(
    df_clean["total_spent"],
    errors = 'coerce'
)

In [86]:
# Convert date time
df_clean['transaction_date'] = pd.to_datetime(
    df_clean['transaction_date'],
    errors = 'coerce'
)

In [ ]:
df_clean['transaction_date'].isna().sum()

In [87]:
# Replacing Missing Values in Categorical Columns

df_clean['item'] = df_clean['item'].fillna('Unknown') 
df_clean['payment_method'] = df_clean['payment_method'].fillna('Unknown') 
df_clean['location'] = df_clean['location'].fillna('Unknown')

In [88]:
df_clean.columns

Index(['transaction_id', 'item', 'quantity', 'price_per_unit', 'total_spent',
       'payment_method', 'location', 'transaction_date'],
      dtype='object')

In [89]:
df_clean.head()

,transaction_id,item,quantity,price_per_unit,total_spent,payment_method,location,transaction_date
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4.0,1.0,NaN,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2.0,5.0,10.0,Unknown,Unknown,2023-04-27
4,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [90]:
# Replacing Missing Numerical Values - total_spent
# Creating temp calculated column

df_clean['calculated_total'] = (df_clean['quantity'] *
                                df_clean['price_per_unit']
)

mask = (
    df_clean['total_spent'].isna() &
    df_clean['quantity'].notna() &
    df_clean['price_per_unit'].notna()
)

df_clean.loc[mask, 'total_spent'] = (
    df_clean.loc[mask, 'quantity'] *
    df_clean.loc[mask, 'price_per_unit']
)

In [91]:
# Replacing Missing Numerical Values - quantity

df_clean.loc[
    df_clean['quantity'].isna() &
    df_clean['total_spent'].notna() &
    df_clean['price_per_unit'].notna(),
    'quantity'
] = (
    df_clean['total_spent'] / df_clean['price_per_unit']
)

In [92]:
# Replacing Missing Numerical Values - price_per_unit

df_clean.loc[
    df_clean['price_per_unit'].isna() &
    df_clean['total_spent'].notna() &
    df_clean['quantity'].notna(),
    'price_per_unit'
] = (
    df_clean['total_spent'] / df_clean['quantity']
)

In [93]:
# Checking missing values

print("Missing Quantity:", df_clean['quantity'].isna().sum())
print("Missing Price:", df_clean['price_per_unit'].isna().sum())
print("Missing Total Spent:", df_clean['total_spent'].isna().sum())

Missing Quantity: 38
Missing Price: 38
Missing Total Spent: 40

In [94]:
# Attempting to find prices based on common items

df_clean[df_clean['price_per_unit'].isna()][
    ['item', 'quantity', 'price_per_unit', 'total_spent']
]

          item  quantity  price_per_unit  total_spent
65    Sandwich       3.0             NaN          NaN
629       Cake       NaN             NaN         12.0
912   Sandwich       NaN             NaN         20.0
1008       Tea       NaN             NaN          3.0
1436       Tea       NaN             NaN          6.0
1482  Smoothie       NaN             NaN         16.0
1674       Tea       2.0             NaN          NaN
1761   Unknown       4.0             NaN          NaN
2229  Sandwich       2.0             NaN          NaN
2289   Unknown       4.0             NaN          NaN
2330     Salad       NaN             NaN          5.0
2585       Tea       3.0             NaN          NaN
3162      Cake       3.0             NaN          NaN
3598  Smoothie       1.0             NaN          NaN
3635    Cookie       NaN             NaN          1.0
3673  Smoothie       2.0             NaN          NaN
3779   Unknown       NaN             NaN         25.0
4021    Cookie       2.0             NaN          NaN
4152   Unknown       2.0             NaN          NaN
5639       Tea       NaN             NaN          6.0
5845  Smoothie       NaN             NaN          8.0
6225    Cookie       NaN             NaN          2.0
6661    Cookie       NaN             NaN          1.0
6674    Coffee       NaN             NaN          4.0
7035     Salad       5.0             NaN          NaN
7230    Cookie       2.0             NaN          NaN
7244  Sandwich       5.0             NaN          NaN
7568    Cookie       5.0             NaN          NaN
7597   Unknown       NaN             NaN          9.0
7686    Coffee       5.0             NaN          NaN
8128  Smoothie       3.0             NaN          NaN
8497  Sandwich       3.0             NaN          NaN
8669      Cake       NaN             NaN          3.0
8975       Tea       NaN             NaN          7.5
9212       Tea       1.0             NaN          NaN
9464      Cake       NaN             NaN          3.0
9819   Unknown       NaN             NaN         20.0
9893     Juice       2.0             NaN          NaN

In [95]:
df_clean.groupby('item')['price_per_unit'].agg(['count', 'median', 'min', 'max'])

          count  median  min  max
item
Cake       1135     3.0  3.0  3.0
Coffee     1163     2.0  2.0  2.0
Cookie     1086     1.0  1.0  1.0
Juice      1170     3.0  3.0  3.0
Salad      1146     5.0  5.0  5.0
Sandwich   1126     4.0  4.0  4.0
Smoothie   1091     4.0  4.0  4.0
Tea        1082     1.5  1.5  1.5
Unknown     963     3.0  1.0  5.0

In [96]:
# Filling missing values for price_per_unit as per median values

df_clean['price_per_unit'] = df_clean['price_per_unit'].fillna(
    df_clean.groupby('item')['price_per_unit'].transform('median')
)

In [97]:
print("Missing Price:", df_clean['price_per_unit'].isna().sum())

Missing Price: 0

In [98]:
df_clean['quantity'] = df_clean['quantity'].fillna(
    df_clean['total_spent'] / df_clean['price_per_unit']
)

In [99]:
df_clean[df_clean['quantity'].isna()][
    ['item', 'quantity', 'price_per_unit', 'total_spent']
]

          item  quantity  price_per_unit  total_spent
236      Salad       NaN             5.0          NaN
278      Juice       NaN             3.0          NaN
641      Juice       NaN             3.0          NaN
738   Sandwich       NaN             4.0          NaN
2796      Cake       NaN             3.0          NaN
3203  Smoothie       NaN             4.0          NaN
3224    Coffee       NaN             2.0          NaN
3401       Tea       NaN             1.5          NaN
4257    Coffee       NaN             2.0          NaN
5841    Cookie       NaN             1.0          NaN
7029    Coffee       NaN             2.0          NaN
7297  Smoothie       NaN             4.0          NaN
8021     Salad       NaN             5.0          NaN
8443  Sandwich       NaN             4.0          NaN
8465    Coffee       NaN             2.0          NaN
8479  Sandwich       NaN             4.0          NaN
8574     Juice       NaN             3.0          NaN
8732    Cookie       NaN             1.0          NaN
9590  Sandwich       NaN             4.0          NaN
9869    Coffee       NaN             2.0          NaN

In [100]:
df_clean.groupby('item')['quantity'].agg(['count', 'median', 'min', 'max'])

          count  median  min       max
item
Cake       1138     3.0  1.0  5.000000
Coffee     1160     3.0  1.0  5.000000
Cookie     1090     3.0  1.0  5.000000
Juice      1168     3.0  1.0  5.000000
Salad      1146     3.0  1.0  5.000000
Sandwich   1127     3.0  1.0  5.000000
Smoothie   1094     3.0  1.0  5.000000
Tea        1088     3.0  1.0  5.000000
Unknown     969     3.0  1.0  8.333333

In [101]:
# Filling missing values for quantity as per median values

df_clean['quantity'] = df_clean['quantity'].fillna(
    df_clean.groupby('item')['quantity'].transform('median')
)

In [102]:
# Converting quanity to integer

df_clean['quantity'] = df_clean['quantity'].round().astype(int)

In [103]:
# Filling missing values for total_spent using calculations

df_clean['total_spent'] = df_clean['total_spent'].fillna(
    df_clean['quantity'] * df_clean['price_per_unit']
)

In [104]:
print("Missing Quantity:", df_clean['quantity'].isna().sum())
print("Missing Price:", df_clean['price_per_unit'].isna().sum())
print("Missing Total Spent:", df_clean['total_spent'].isna().sum())

Missing Quantity: 0
Missing Price: 0
Missing Total Spent: 0

In [105]:
print("Quantity <= 0:", (df_clean['quantity'] <= 0).sum())
print("Price <= 0:", (df_clean['price_per_unit'] <= 0).sum())
print("Total spent <= 0:", (df_clean['total_spent'] <= 0).sum())

Quantity <= 0: 0
Price <= 0: 0
Total spent <= 0: 0

In [106]:
df_clean.dtypes

transaction_id              object
item                        object
quantity                     int32
price_per_unit             float64
total_spent                float64
payment_method              object
location                    object
transaction_date    datetime64[ns]
calculated_total           float64
dtype: object

In [107]:
df_clean.head()

,transaction_id,item,quantity,price_per_unit,total_spent,payment_method,location,transaction_date,calculated_total
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08,4.0
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16,12.0
2,TXN_4271903,Cookie,4,1.0,4.0,Credit Card,In-store,2023-07-19,4.0
3,TXN_7034554,Salad,2,5.0,10.0,Unknown,Unknown,2023-04-27,10.0
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11,4.0

In [ ]:
df_clean.duplicated().sum()

In [108]:
# Exporting cleaned dataset

df_clean.to_csv(r'C:\DSML\Jobs\2026\Internship\SkillAudit\CafeProject\data\processed\dirty_cafe_sales_cleaned.csv', index=False)

In [109]:
df_clean.head()

,transaction_id,item,quantity,price_per_unit,total_spent,payment_method,location,transaction_date,calculated_total
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08,4.0
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16,12.0
2,TXN_4271903,Cookie,4,1.0,4.0,Credit Card,In-store,2023-07-19,4.0
3,TXN_7034554,Salad,2,5.0,10.0,Unknown,Unknown,2023-04-27,10.0
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11,4.0